name: Build and deploy Node.js app to Azure Web App - autocrew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      # Step 1: Checkout code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies for the server
      - name: Install server dependencies
        run: |
          cd server
          npm install
          npm run build --if-present
          npm run test --if-present

      # Step 4: Install dependencies for the client
      - name: Install client dependencies
        run: |
          cd client
          npm install
          npm run build --if-present
          npm run test --if-present

      # Step 5: Upload artifacts for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
          client/dist
          server/index.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      # Step 1: Download artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D8AD88A86984F5DA3060148CD0D42A7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1136D22EC42145CD85ECFC89C456D497 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C5A68851ABE14788BBE5E789057B52D1 }}

      # Step 3: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'autocrew'
          slot-name: 'Production'
          package: ./node-app
